# Generated by Django 5.2.5 on 2025-10-30 16:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('coding', 'Coding Challenge')], default='multiple_choice', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('options', models.JSONField(blank=True, help_text='Multiple choice options (for multiple_choice type)', null=True)),
                ('correct_answer', models.TextField(help_text='The correct answer')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer', null=True)),
                ('category', models.CharField(blank=True, help_text='Question category/topic', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Whether this question was generated by AI')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('single', 'Single Player'), ('multiplayer', 'Multiplayer'), ('coding_battle', 'Coding Battle')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('max_players', models.IntegerField(default=1, help_text='Maximum number of players allowed')),
                ('current_question_index', models.IntegerField(default=0, help_text='Current question being displayed')),
                ('time_limit', models.IntegerField(default=15, help_text='Time limit per question in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('total_score', models.IntegerField(default=0, help_text='Total accumulated score across all games')),
                ('games_played', models.IntegerField(default=0, help_text='Number of games played')),
                ('win_rate', models.FloatField(default=0.0, help_text='Win rate percentage')),
                ('avatar', models.ImageField(blank=True, help_text='User avatar image', null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Submitted code')),
                ('language', models.CharField(default='python', help_text='Programming language', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Evaluation'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in KB', null=True)),
                ('output', models.TextField(blank=True, help_text='Program output', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if any', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Order of the question in the session')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(help_text='Questions in this session', through='quiz.SessionQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Current score in the session')),
                ('correct_answers', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('total_answers', models.IntegerField(default=0, help_text='Total number of answers given')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizsession')),
            ],
            options={
                'unique_together': {('player', 'session')},
            },
        ),
    ]
