# Generated by Django 5.2.5 on 2025-11-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('description', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('test_cases', models.JSONField(help_text='List of {input, expected_output} dictionaries')),
            ],
        ),
        migrations.CreateModel(
            name='CodingBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.codingproblem')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_index', models.IntegerField(help_text='1 or 2')),
                ('language_id', models.IntegerField()),
                ('source_code', models.TextField()),
                ('passed_count', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('runtime', models.FloatField(default=0.0, help_text='Max runtime in seconds')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('status_text', models.CharField(default='Pending', max_length=50)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.codingbattle')),
            ],
        ),
    ]
