# Generated by Django 5.2.5 on 2025-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_codingproblem_codingbattle_playersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Initial code for the user', null=True),
        ),
    ]
