# Generated by Django 5.2.5 on 2025-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizsession_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='difficulty_level',
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='test_cases',
            field=models.JSONField(help_text='List of test cases'),
        ),
    ]
