# Generated by Django 5.2.5 on 2025-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quizsession_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='difficulty_level',
            field=models.CharField(default='mixed', help_text='Difficulty level of the session', max_length=10),
        ),
    ]
